### ISSUE TITLE
Arguments passed into `load` are being discarded.

### ISSUE THREAD

**Issue by fluffywaffles** [pyrolabs/overwire#3]
```
export default {
  load: () => {
    loadScripts()
      .then(() => {
        determineRequiredBundles()
        loadRequiredBundles()
      })
  }
}
```

If I call `load([ './my-script.js' ])` it's not going to pass that argument into `loadScripts` and my script will not  load. Unless you're using some kind of evil webpack magic to compile this so that arguments are always passed, I don't think your README is correct.

**Comment by prescottprue** [comment]
@fluffywaffles This library was actually just migrated over to being built this way from a demo application.

You are correct about the README and the API not being valid yet. Over the next few days it will change quite a bit.

**Comment by sbolel** [comment]
Nice catch @fluffywaffles, thank you!

This seems to be related to #4
