### ISSUE TITLE
Simplify API?

### ISSUE THREAD

**Issue by fluffywaffles** [pyrolabs/overwire#4]
Since you named the parameter `scriptUrlsArr` and your README example clearly expects the argument to be an array and your tests (well, test) uses an array as the only argument, you can probably remove the [branch of the code that tests if the type of the argument is a string and handles that case](https://github.com/pyrolabs/overwire/blob/master/src/index.js#L58). That case should cause an error, not succeed silently. It's not the correct usage of the API. Correct me if wrong.

**Comment by sbolel** [comment]
Correct. Great catch! 

We'll get a PR started, help is always appreciated :)
