### ISSUE TITLE
LocalStorage Limitations

### ISSUE THREAD

**Issue by fluffywaffles** [pyrolabs/overwire#6]
https://www.sitepoint.com/html5-local-storage-revisited/

The highest LocalStorage limit is 10mb but goes as low as 5mb, per-origin. Naively built Angular 2 Bundles can easily exceed that size (think CMS -- lots of routes and components). Plus LocalStorage blocks the UI thread according to the above article. See also: 

https://hacks.mozilla.org/2012/03/there-is-no-simple-solution-for-local-storage/

Seems like you'd be better off with a cdn since that hits the (much larger and faster) browser cache.

**Comment by sbolel** [comment]
Very valid. This was a temporary quick-and-dirty solution.

CDN is a good option. How do you suggest approaching this change?
